#!/bin/sh -e

PREFIX=""
SOURCE="./"

if [ -n "$1" ] ; then
    PREFIX=$1
fi

if [ -n "$2" ] ; then
    SOURCE=$2
fi


${PREFIX}black -t py38 --check --diff ${SOURCE}
${PREFIX}mypy \
    --cache-dir=/dev/null \
    --no-strict-optional \
    --follow-imports=skip \
    --namespace-packages \
    ${SOURCE}meow/validators
