#!/bin/sh -e

PREFIX=""
SOURCE="./"

if [ -n "$1" ] ; then
    PREFIX=$1
fi

if [ -n "$2" ] ; then
    SOURCE=$2
fi

${PREFIX}mypy \
    --config-file=${SOURCE}.mypy_test.ini \
    --cache-dir=/dev/null \
    --show-absolute-path \
    ${SOURCE} | tee ${SOURCE}mypy_tests.txt

${PREFIX}python -m pytest \
    -s \
    -p no:cacheprovider \
    --cov ${SOURCE}meow \
    --cov-report term-missing \
    --maxfail=2
